# -*- coding: utf-8 -*-
"""Deploy-8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11zmOSgimiinJGgxDYlBnamgAbEHJpLuA
"""

#!pip install streamlit
import pickle
import pandas as pd
import streamlit as st
from sklearn.preprocessing import LabelEncoder, StandardScaler


features = [
    'age', 'hypertension', 'heart_disease', 'avg_glucose_level', 'bmi',
    'gender_Male', 'gender_Other', 'ever_married_Yes', 'work_type_Never_worked',
    'work_type_Private', 'work_type_Self-employed', 'work_type_children',
    'Residence_type_Urban', 'smoking_status_formerly smoked',
    'smoking_status_never smoked', 'smoking_status_smokes'
]

st.sidebar.title('Stroke Prediction')
st.sidebar.markdown('---')
gender=st.sidebar.selectbox("Select gender of the patient", ('Male','Female'))
hyper=st.sidebar.selectbox("Select if patient has Hypertension",('Yes','No'))
ever_married=st.sidebar.selectbox("Select if patient is married",('Yes','No'))
residence_type=st.sidebar.selectbox("Select if patient lives in Urban Area",
 ('Yes','No'))
heart_dis=st.sidebar.selectbox("Select if the patient has Heart Disease",
 ('Yes','No'))
work_type=st.sidebar.radio('Select work type',('Never worked','Private',
                                               'Self-employed','children'))
smoking_status=st.sidebar.radio('Select smoking status',('formerly smoked',
                                                         'never smoked','smokes'))
bmi=st.sidebar.slider("BMI of the patient:", 0, 100, step=2)
avg_glucose=st.sidebar.slider("Glucose Level of patient", 0,400, step=5)
age=st.sidebar.slider("Age of the patient", 0,100, step=1)

stroke_feat  = {
    'age': ['age'],
    'hypertension': ['hypertension'],
    'heart_disease': ['heart_disease'],
    'avg_glucose_level': ['avg_glucose_level'],
    'bmi': ['bmi'],
    'gender_Male': 1 if ['gender'] == 'Male' else 0,
    'gender_Other': 1 if ['gender'] == 'Other' else 0,
    'ever_married_Yes': 1 if ['ever_married'] == 'Yes' else 0,
    'work_type_Never_worked': 1 if ['work_type'] == 'Never_worked' else 0,
    'work_type_Private': 1 if ['work_type'] == 'Private' else 0,
    'work_type_Self-employed': 1 if ['work_type'] == 'Self-employed' else 0,
    'work_type_children': 1 if ['work_type'] == 'childre' else 0,
    'Residence_type_Urban': 1 if ['Residence_type'] == 'Urban' else 0,
    'smoking_status_formerly smoked': 1 if ['smoking_status'] == 'formerly smoked' else 0,
    'smoking_status_never smoked': 1 if ['smoking_status'] == 'never smoked' else 0,
    'smoking_status_smokes': 1 if ['smoking_status'] == 'smokes' else 0
}

with open('scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)

stroke_df = pd.DataFrame([stroke_feat],columns=features)

input_scaled = scaler.transform(stroke_df)

prediction = model.predict(input_scaled)
st.write(prediction)
print(f'Predicted Stroke Risk: {prediction[0]}')