# -*- coding: utf-8 -*-
"""Deployment-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1maXsGK41np704jJ4OK9LLOgDCYJvWL5E
"""

!pip install streamlit
import pickle
import pandas as pd
import streamlit as st
from sklearn.preprocessing import LabelEncoder
import xgboost as xgb


st.sidebar.title('Stroke Prediction')
st.sidebar.markdown('---')
gender=st.sidebar.selectbox("Select gender of the patient", ('Male','Female'))
hyper=st.sidebar.selectbox("Select if patient has Hypertension",('Yes','No'))
ever_married=st.sidebar.selectbox("Select if patient is married",('Yes','No'))
residence_type=st.sidebar.selectbox("Select if patient lives in Urban Area",
 ('Yes','No'))
heart_dis=st.sidebar.selectbox("Select if the patient has Heart Disease",
 ('Yes','No'))
work_type=st.sidebar.radio('Select work type',('Never worked','Private',
                                               'Self-employed','children'))
smoking_status=st.sidebar.radio('Select smoking status',('formerly smoked',
                                                         'never smoked','smokes'))
bmi=st.sidebar.slider("BMI of the patient:", 0, 100, step=2)
avg_glucose=st.sidebar.slider("Glucose Level of patient", 0,400, step=5)
age=st.sidebar.slider("Age of the patient", 0,100, step=1)
#heart_disease = int(heart_dis == "Yes")
#hypertension = int(hyper == "Yes")

conf_stroke = {
    'age': ['age'],
    'hypertension': ['hypertension'],
    'heart_disease': ['heart_disease'],
    'avg_glucose_level': ['avg_glucose_level'],
    'bmi': ['bmi'],
    'gender_Male': int(['gender'] == 'Male'),
    'gender_Other': int(['gender'] == 'Other'),
    'ever_married_Yes': int(['ever_married'] == 'Yes'),
    'work_type_Never_worked': int(['work_type'] == 'Never_worked'),
    'work_type_Private': int(['work_type'] == 'Private'),
    'work_type_Self-employed': int(['work_type'] == 'Self-employed'),
    'work_type_children': int(['work_type'] == 'children'),
    'Residence_type_Urban': int(['Residence_type'] == 'Urban'),
    'smoking_status_formerly smoked': int(['smoking_status'] == 'formerly smoked'),
    'smoking_status_never smoked': int(['smoking_status'] == 'never smoked'),
    'smoking_status_smokes': int(['smoking_status'] == 'smokes')
}

input_df = pd.DataFrame.from_dict([conf_stroke])

#with open ('final_model.pkl', 'rb') as file:
try:
    with open('final_model.pkl', 'rb') as file:
        model = pickle.load(file)
except EOFError:
    st.error("Error: The model file 'final_model.pkl' is corrupted or incomplete. Please check the file or retrain the model.")
    # You might want to exit the script or handle the error in a way that makes sense for your application.
except FileNotFoundError:
    st.error("Error: The model file 'final_model.pkl' was not found. Please make sure it is in the correct directory.")
#model = pickle.load(open('final_model.pkl','rb'))
#enc=pickle.load(open('final_model.pkl', 'rb'))

#df.loc[:,["final_model","xgb_model_last"]]

#df.loc[:,["final_model","xgb_model_last"]] = enc.fit_transform(df.loc[:,
 #["final_model","xgb_model_last"]])

st.header("The information of your patient:")
st.table(input_df)

st.subheader("Press predict if the patients' details are correct")

if st.button("Predict Risk of Stroke"):
  try:
    prediction = model.predict(input_df)
    if prediction[0] == 1:
      st.write("The model predicts a high risk of stroke.")
    else:
      st.write("The model predicts a low risk of stroke.")
  except Exception as e:
        st.write(f"Error in prediction: {e}")

#type conversion
for col in input_df.columns:
    if input_df[col].dtype == 'object' or input_df[col].dtype.name == 'category':
        input_df[col] = input_df[col].astype(str)
        input_df[col] = LabelEncoder().fit_transform(input_df[col])
    elif input_df[col].dtype == 'bool':
        input_df[col] = input_df[col].astype(int)
input_df = input_df.astype({col: str for col in input_df.select_dtypes(include='category').columns})


def preprocess_input(df: pd.DataFrame) -> pd.DataFrame:
    """
    Preprocess incoming data for XGBoost prediction.
    Converts numeric strings to floats and categoricals to proper types.
    """
    # Define columns
    numeric_cols = ['age', 'avg_glucose_level', 'bmi']
    categorical_cols = ['hypertension', 'heart_disease', 'gender_Male',
                        'gender_Other','ever_married_Yes',
                        'work_type_Never_worked','work_type_Private',
                        'work_type_Self-employed','work_type_children',
                        'Residence_type_Urban','smoking_status_formerly smoked',
                        'smoking_status_never smoked','smoking_status_smokes']
    # Coerce numeric columns to float
    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col], errors='coerce')

    # Convert categorical columns to 'category' dtype
    for col in categorical_cols:
        df[col] = df[col].astype('category')

    # Optional: fill missing values (customize as needed)
    df = df.fillna(0)

    return df

print(input_df.dtypes)


# Preprocess
df_clean = preprocess_input(input_df)

# Create DMatrix
dmat = xgb.DMatrix(df_clean, enable_categorical=True)

# Predict
prediction = model.predict(dmat)

print(f"Predicted Stroke Risk: {prediction[0]}")

#st.success("The patient is predicted to have a stroke is €{} \u00B1 {}. ".
               #format(int(prediction[0]), int(prediction[0])*0.0918))